-- Remover todas as tabelas da Evolution API (não mais utilizada)

-- Tabelas de sessão primeiro (dependências)
DROP TABLE IF EXISTS "ChamaaiSession" CASCADE;
DROP TABLE IF EXISTS "DifySession" CASCADE;
DROP TABLE IF EXISTS "EvoaiSession" CASCADE;
DROP TABLE IF EXISTS "EvolutionBotSession" CASCADE;
DROP TABLE IF EXISTS "FlowiseSession" CASCADE;
DROP TABLE IF EXISTS "N8nSession" CASCADE;
DROP TABLE IF EXISTS "OpenaiSession" CASCADE;
DROP TABLE IF EXISTS "TypebotSession" CASCADE;

-- Tabelas de credenciais
DROP TABLE IF EXISTS "Chamaai" CASCADE;
DROP TABLE IF EXISTS "DifyCreds" CASCADE;
DROP TABLE IF EXISTS "Evoai" CASCADE;
DROP TABLE IF EXISTS "FlowiseCreds" CASCADE;
DROP TABLE IF EXISTS "N8nCreds" CASCADE;
DROP TABLE IF EXISTS "OpenaiCreds" CASCADE;

-- Tabelas de integrações
DROP TABLE IF EXISTS "Dify" CASCADE;
DROP TABLE IF EXISTS "Flowise" CASCADE;
DROP TABLE IF EXISTS "N8n" CASCADE;
DROP TABLE IF EXISTS "OpenaiBot" CASCADE;
DROP TABLE IF EXISTS "EvolutionBot" CASCADE;
DROP TABLE IF EXISTS "Typebot" CASCADE;
DROP TABLE IF EXISTS "Chatwoot" CASCADE;
DROP TABLE IF EXISTS "Integration" CASCADE;

-- Tabelas de mensagens e contatos
DROP TABLE IF EXISTS "Message" CASCADE;
DROP TABLE IF EXISTS "MessageUpdate" CASCADE;
DROP TABLE IF EXISTS "Chat" CASCADE;
DROP TABLE IF EXISTS "Contact" CASCADE;
DROP TABLE IF EXISTS "Label" CASCADE;
DROP TABLE IF EXISTS "Template" CASCADE;

-- Tabelas de configuração
DROP TABLE IF EXISTS "Instance" CASCADE;
DROP TABLE IF EXISTS "Session" CASCADE;
DROP TABLE IF EXISTS "Setting" CASCADE;
DROP TABLE IF EXISTS "Settings" CASCADE;
DROP TABLE IF EXISTS "Proxy" CASCADE;

-- Tabelas de webhook/messaging
DROP TABLE IF EXISTS "Webhook" CASCADE;
DROP TABLE IF EXISTS "Websocket" CASCADE;
DROP TABLE IF EXISTS "Nats" CASCADE;
DROP TABLE IF EXISTS "Rabbitmq" CASCADE;
DROP TABLE IF EXISTS "Sqs" CASCADE;

-- Tabelas de WhatsApp Business
DROP TABLE IF EXISTS "wa_Business" CASCADE;
DROP TABLE IF EXISTS "wa_Presence" CASCADE;
DROP TABLE IF EXISTS "wa_PrivacySettings" CASCADE;